INSERT INTO AGENCY (
    ID,
    TENANT_ID,
    NAME,
    DESCRIPTION,
    POSTCODE,
    CITY,
    IS_TEAM_AGENCY,
    CONSULTING_TYPE,
    IS_OFFLINE,
    IS_EXTERNAL,
    CREATE_DATE,
    UPDATE_DATE,
    DELETE_DATE,
    COUNSELLING_RELATIONS
)
SELECT
    246,
    21,
    'Caritasverband Wismar',
    'Demo/initial-delivery counselling center for public registration baseline checks.',
    '23966',
    'Wismar',
    0,
    1,
    0,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    NULL,
    'RELATIVE_COUNSELLING,SELF_COUNSELLING,PARENTAL_COUNSELLING'
WHERE NOT EXISTS (
    SELECT 1 FROM AGENCY WHERE ID = 246
);

UPDATE AGENCY
SET
    TENANT_ID = 21,
    NAME = 'Caritasverband Wismar',
    CONSULTING_TYPE = 1,
    IS_OFFLINE = 0,
    IS_EXTERNAL = 0,
    DELETE_DATE = NULL,
    UPDATE_DATE = CURRENT_TIMESTAMP
WHERE ID = 246;

INSERT INTO AGENCY_POSTCODE_RANGE (
    ID,
    TENANT_ID,
    AGENCY_ID,
    POSTCODE_FROM,
    POSTCODE_TO,
    CREATE_DATE,
    UPDATE_DATE
)
SELECT
    900000001,
    21,
    246,
    '00000',
    '99999',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE EXISTS (
    SELECT 1 FROM AGENCY WHERE ID = 246
)
AND NOT EXISTS (
    SELECT 1
    FROM AGENCY_POSTCODE_RANGE
    WHERE AGENCY_ID = 246
      AND POSTCODE_FROM <= '88885'
      AND POSTCODE_TO >= '88885'
);

MERGE INTO AGENCY_TOPIC (
    ID,
    AGENCY_ID,
    TOPIC_ID,
    CREATE_DATE,
    UPDATE_DATE,
    PUBLICATION_STATUS,
    PUBLICATION_STATUS_IMPRINT
)
KEY (AGENCY_ID, TOPIC_ID)
VALUES (
    900000002,
    246,
    2,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'DRAFT',
    'DRAFT'
);

MERGE INTO AGENCY_TOPIC (
    ID,
    AGENCY_ID,
    TOPIC_ID,
    CREATE_DATE,
    UPDATE_DATE,
    PUBLICATION_STATUS,
    PUBLICATION_STATUS_IMPRINT
)
KEY (AGENCY_ID, TOPIC_ID)
VALUES (
    900000010,
    246,
    10,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'DRAFT',
    'DRAFT'
);
