flowchart TD
  AgencyService[ORISO AgencyService] --> ApplicationSettings[Application Settings Service]
  AgencyService --> Appointment[Appointment Service]
  AgencyService --> ConsultingType[Consulting Type Service]
  AgencyService --> Tenant[Tenant Service]
  AgencyService --> Topic[Topic Service]
  AgencyService --> UserAdmin[User Admin Service]
