name: AgencyService Branch Validation

on:
  push:
    branches-ignore:
    - main
    - dev

jobs:
  validate:
    name: test and build AgencyService
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Run AgencyService tests and build
      uses: ./.github/actions/maven-build
      with:
        java_version: '17'
